# Generated by Django 3.1 on 2020-08-19 04:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=120, verbose_name='Last Name')),
                ('phone', models.CharField(max_length=20, verbose_name='Contact Phone')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='Whatsapp No.')),
                ('email_address', models.EmailField(blank=True, max_length=254, verbose_name='Email Address')),
                ('address', models.CharField(blank=True, max_length=300)),
                ('city', models.CharField(blank=True, max_length=30, verbose_name='City')),
                ('zip_code', models.CharField(blank=True, max_length=12, verbose_name='Zip/Post Code')),
                ('country', models.CharField(max_length=300, verbose_name='Country')),
                ('wallet', models.CharField(blank=True, max_length=43)),
                ('web', models.URLField(blank=True, verbose_name='Web Address')),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('exchange_from', models.CharField(choices=[('Bitcoin', 'BTC'), ('Etherem', 'ETH'), ('UGX', 'UGX'), ('NGN', 'NGN'), ('RWF', 'RWF'), ('CHF', 'CHF'), ('USD', 'USD')], default='BTC', max_length=10)),
                ('exchange_to', models.CharField(choices=[('Bitcoin', 'BTC'), ('Etherem', 'ETH'), ('UGX', 'UGX'), ('NGN', 'NGN'), ('RWF', 'RWF'), ('CHF', 'CHF'), ('USD', 'USD')], default='UGX', max_length=10)),
                ('exchange_amount', models.CharField(max_length=20)),
                ('exchange_percentage', models.CharField(max_length=20)),
                ('exchange_fees', models.CharField(max_length=20)),
                ('wallet_source', models.CharField(max_length=20)),
                ('wallet_destination', models.CharField(max_length=43)),
                ('mobilemoney_no', models.CharField(max_length=20)),
                ('whatsapp_no', models.CharField(max_length=15)),
                ('bank_details', models.CharField(max_length=200)),
                ('tradetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('draft', 'Draft')], default='draft', max_length=10)),
                ('customer_feedback', models.TextField()),
                ('comment', models.TextField()),
                ('salesperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-tradetime',),
            },
        ),
    ]
